config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'courses/new', to: 'courses#new'

  get 'about', to: 'pages#about'
  resources :students

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
has_many :students

validates :title, presence: true,
   length: { minimum: 4, maximum: 12 },
   uniqueness: { case_sensitive: false }

   validates :description, presence: true,
      length: { minimum: 10, maximum: 300 },
      uniqueness: { case_sensitive: false }

end

app/models/student.rb
class Student < ApplicationRecord
before_save {self.email = email.downcase }
belongs_to :course, optional: true

  validates :username, presence: true,
     length: { minimum: 4, maximum: 12 },
     uniqueness: { case_sensitive: false }

  validates :name, presence: true,
   length: { minimum: 4, maximum: 12 },
   uniqueness: { case_sensitive: false }

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                 length: { maximum: 105 },
                 uniqueness: { case_sensitive: false },
                 format: { with: VALID_EMAIL_REGEX }

has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user

  helper_method :current_user, :logged_in?, :students_name
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def students_name
    Student.find(session[:student_id]).name if session[:student_id]
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  skip_before_action :require_user

  def index
    @courses = Course.all
    @student == current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

skip_before_action :require_user

def about
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create]

  def new

  end


  def create
    student = Student.find_by(email: params[:sessions][:email].downcase)
    if student && student.authenticate(params[:sessions][:password])
      session[:student_id] = student.id
      flash[:notice] = "You have successfully logged in"
      redirect_to student

    else
      flash.now[:notice] = "Your credentals were not correct"
      render 'new'
    end

  end



  def destroy
    session[:student_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end




end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create]
before_action :set_student, only: [:show, :edit, :update]

def index
  @students = Student.all
end

def show

end

def new
  @student = Student.new
end

def edit
  if @student == current_user
  else
    flash[:notice] = "You can only edit your own profile"
    redirect_to students_path
  end

end

def update

  if @student.update(student_params)
    flash[:notice] = "You have successfully updated your profile"
    redirect_to student_path(@student)
  else
    render 'edit'
  end
end


def create
  @student = Student.new(student_params)
  if @student.save
    flash[:notice] = "You have successfully signed up"
    redirect_to student_path(@student)

  else
    render 'new'
  end
end

private

def student_params
  params.require(:student).permit(:name, :username, :email, :password, :password_confirmation, :course_id)
end

def set_student
  @student = Student.find(params[:id])
end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_link

    if logged_in?
     link_to("Log out", logout_path, method: :delete)
     
    else
      link_to("Log in", login_path)
    end

  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 align="center"> Course Listing </h3>
  </div>
</div>


<div class="row">
  <% @courses.each do |k| %>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= k.title %></span>
        <p><%= k.description %></p>
      </div>
      <div class="card-action">
        <a href="#">ENROLL</a>
        <a href="#">INFO</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1> new course page </h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">UniversityApp</h5>
            <p class="grey-text text-lighten-4">The future of development training</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Information</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2019 UniversityApp
        <a class="grey-text text-lighten-4 right" href="#!">About</a>
        </div>
      </div>
    </footer>

app/views/layouts/_navbar.html.erb
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>

  </ul>


    <ul id="dropdown2" class="dropdown-content">
      <li><%= session_link %></li>
      <li><a href="#!">two</a></li>
      <li class="divider"></li>
      <li><a href="#!">three</a></li>
    </ul>

  <nav>
      <div class="nav-wrapper container">

          <%= link_to 'UniversityApp', root_path, class: "brand-logo right" %>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="left hide-on-med-and-down ">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
            <li><%= link_to 'Students', students_path %></li>
            <% else %>
            <li><%= link_to "Sign up", new_student_path %></li>
            <% end %>
            <!-- dropdown trigger-->
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account <i class="material-icons right">arrow_drop_down</i></a></li>
            <li> <%= logged_in? ? "Signed in as:" + " " + students_name : " " %> </li>
          </ul>

      </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><%= link_to 'Courses', root_path %></li>
    <li><%= link_to 'Students', students_path %></li>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <div class="container" id="fade">
        <br>
        <% flash.each do |key, message| %>
        <%= message %>
        <% end %>
      </div>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<h1> about page </h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<br>
    <strong><%= pluralize(obj.errors.count, "error") %>
    prohibited your profile from being created:</strong>
      <ul>
        <% obj.errors.full_messages.each do |m| %>
        <li><%= m %></<li>
        <% end %>
      </ul>
    <% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>


<div class="row">
  <div class="col s12">
    <h3><%= @student.new_record? ? "Sign up" : "Edit your profile" %></h3>
  </div>
</div>




    <div class="row">
      <div class="col s6">
          <%= form_for(@student, :html => { class: "col 12", role: "form"}) do |f| %>
            <br>
            <div class="row">
                <%= f.label :name %>
                <%= f.text_field :name, placeholder: "enter your name", class: "validate", id: "name" %>
            </div>

            <div class="row">
              <%= f.label :username %>
              <%= f.text_field :username, placeholder: "enter your username", class: "validate", id: "username" %>
              </div>


            <div class="row">
                <%= f.label :email %>
                <%= f.email_field :email, placeholder: "enter your email", class: "validate", id: "email" %>
            </div>

            <div class="row">
                <%= f.label :password %>
                <%= f.password_field :password, placeholder: "enter your password", class: "validate", id: "password" %>
            </div>

            <div class="row">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, placeholder: "confirm your password", class: "validate", id: "password" %>
            </div>

            <div class="row">

            <%= f.select(:course_id) do %>
              <% [['CS111: Intro to Computer Science', 1], ['CS112: Data Structures', 2], ['CS205: Intro to Linear Algebra', 3]].each do |c| %>
                <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
            <%end %>
            </div>


            <div class="row">
              <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>SIGN UP'.html_safe : '<i class="material-icons right">arrow_forward</i>SUBMIT UPDATES'.html_safe, class: "btn teal waves-effect waves-light") %>
            </div>
          <% end %>
      </div>
    </div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 align="center"> Students Directory </h3>
  </div>
</div>


<div class="row">
  <% @students.each do |k| %>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"> <%= k.name %></span>
        <p>Username: <%= k.username %></p>
        <p>Email: <%= k.email %></p>
        <p>Course enrollments:</p>
        <p><%= k.course.title %></p>
      </div>
      <div class="card-action">
        <%= link_to "VIEW PROFILE", student_path(k) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"> <%= @student.name %></span>
      <p>Username: <%= @student.username %></p>
      <p>Email: <%= @student.email %></p>
      <p>Course enrollments:</p>
      <p><%= @student.course.title %></p>
    </div>
  </div>

 <% if logged_in? && @student == current_user %>
    <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
  <% end %>
</div>